# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infaas/proto/internal/placement.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'infaas/proto/internal/placement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from infaas.proto.internal import infaas_request_status_pb2 as infaas_dot_proto_dot_internal_dot_infaas__request__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%infaas/proto/internal/placement.proto\x12\x0finfaas.internal\x1a\x31infaas/proto/internal/infaas_request_status.proto\"b\n\x0bScaleOption\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x13\n\x0bsrc_variant\x18\x02 \x01(\t\x12\x13\n\x0b\x64st_variant\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x05 \x01(\x01\"g\n\x12ScaleActionRequest\x12\x12\n\nsrc_worker\x18\x01 \x01(\t\x12-\n\x07options\x18\x02 \x03(\x0b\x32\x1c.infaas.internal.ScaleOption\x12\x0e\n\x06reason\x18\x03 \x01(\t\"K\n\x13ScaleActionResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus2h\n\tPlacement\x12[\n\x0cRequestScale\x12#.infaas.internal.ScaleActionRequest\x1a$.infaas.internal.ScaleActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infaas.proto.internal.placement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCALEOPTION']._serialized_start=109
  _globals['_SCALEOPTION']._serialized_end=207
  _globals['_SCALEACTIONREQUEST']._serialized_start=209
  _globals['_SCALEACTIONREQUEST']._serialized_end=312
  _globals['_SCALEACTIONRESPONSE']._serialized_start=314
  _globals['_SCALEACTIONRESPONSE']._serialized_end=389
  _globals['_PLACEMENT']._serialized_start=391
  _globals['_PLACEMENT']._serialized_end=495
# @@protoc_insertion_point(module_scope)
