# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infaas.proto.internal import placement_pb2 as infaas_dot_proto_dot_internal_dot_placement__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infaas/proto/internal/placement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlacementStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestScale = channel.unary_unary(
                '/infaas.internal.Placement/RequestScale',
                request_serializer=infaas_dot_proto_dot_internal_dot_placement__pb2.ScaleActionRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_internal_dot_placement__pb2.ScaleActionResponse.FromString,
                _registered_method=True)


class PlacementServicer:
    """Missing associated documentation comment in .proto file."""

    def RequestScale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlacementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestScale': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestScale,
                    request_deserializer=infaas_dot_proto_dot_internal_dot_placement__pb2.ScaleActionRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_internal_dot_placement__pb2.ScaleActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infaas.internal.Placement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infaas.internal.Placement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Placement:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.Placement/RequestScale',
            infaas_dot_proto_dot_internal_dot_placement__pb2.ScaleActionRequest.SerializeToString,
            infaas_dot_proto_dot_internal_dot_placement__pb2.ScaleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
