# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infaas.proto.internal import sys_monitor_pb2 as infaas_dot_proto_dot_internal_dot_sys__monitor__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infaas/proto/internal/sys_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SysStatusStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScaleUpModel = channel.unary_unary(
                '/infaas.internal.SysStatus/ScaleUpModel',
                request_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleResponse.FromString,
                _registered_method=True)
        self.ScaleDownModel = channel.unary_unary(
                '/infaas.internal.SysStatus/ScaleDownModel',
                request_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleResponse.FromString,
                _registered_method=True)
        self.MigrateModel = channel.unary_unary(
                '/infaas.internal.SysStatus/MigrateModel',
                request_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateResponse.FromString,
                _registered_method=True)
        self.CreateModel = channel.unary_unary(
                '/infaas.internal.SysStatus/CreateModel',
                request_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateResponse.FromString,
                _registered_method=True)
        self.ProfileVariant = channel.unary_unary(
                '/infaas.internal.SysStatus/ProfileVariant',
                request_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ProfileRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ProfileResponse.FromString,
                _registered_method=True)


class SysStatusServicer:
    """Missing associated documentation comment in .proto file."""

    def ScaleUpModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScaleDownModel(self, request, context):
        """Unload the variant from this worker (numreplicas ignored: GPU_MAX_REPLICAS = 1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateModel(self, request, context):
        """Load the variant on this worker (blocks until Active).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProfileVariant(self, request, context):
        """infaas_k8s: one-time profiling of a variant on this worker's GPU.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SysStatusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScaleUpModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ScaleUpModel,
                    request_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleResponse.SerializeToString,
            ),
            'ScaleDownModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ScaleDownModel,
                    request_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleResponse.SerializeToString,
            ),
            'MigrateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateModel,
                    request_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateResponse.SerializeToString,
            ),
            'CreateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModel,
                    request_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateResponse.SerializeToString,
            ),
            'ProfileVariant': grpc.unary_unary_rpc_method_handler(
                    servicer.ProfileVariant,
                    request_deserializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ProfileRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infaas.internal.SysStatus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infaas.internal.SysStatus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SysStatus:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScaleUpModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.SysStatus/ScaleUpModel',
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleRequest.SerializeToString,
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScaleDownModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.SysStatus/ScaleDownModel',
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleRequest.SerializeToString,
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ScaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.SysStatus/MigrateModel',
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateRequest.SerializeToString,
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.SysStatus/CreateModel',
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateRequest.SerializeToString,
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.CreateMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProfileVariant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.SysStatus/ProfileVariant',
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ProfileRequest.SerializeToString,
            infaas_dot_proto_dot_internal_dot_sys__monitor__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
