# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infaas/proto/internal/sys_monitor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'infaas/proto/internal/sys_monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from infaas.proto.internal import infaas_request_status_pb2 as infaas_dot_proto_dot_internal_dot_infaas__request__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'infaas/proto/internal/sys_monitor.proto\x12\x0finfaas.internal\x1a\x31infaas/proto/internal/infaas_request_status.proto\"2\n\x0cScaleRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x13\n\x0bnumreplicas\x18\x02 \x01(\x05\"E\n\rScaleResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"L\n\x14\x43reateMigrateRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x10\n\x08hardware\x18\x02 \x01(\t\x12\x13\n\x0bnumreplicas\x18\x03 \x01(\x05\"^\n\x15\x43reateMigrateResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\x12\x0f\n\x07load_ms\x18\x02 \x01(\x01\"j\n\x0eProfileRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x0c\n\x04runs\x18\x03 \x01(\x05\x12\x13\n\x0bsat_seconds\x18\x04 \x01(\x01\x12\x17\n\x0fsat_concurrency\x18\x05 \x01(\x05\"]\n\x0fProfileResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\x12\x14\n\x0cprofile_json\x18\x02 \x01(\t2\xc7\x03\n\tSysStatus\x12O\n\x0cScaleUpModel\x12\x1d.infaas.internal.ScaleRequest\x1a\x1e.infaas.internal.ScaleResponse\"\x00\x12Q\n\x0eScaleDownModel\x12\x1d.infaas.internal.ScaleRequest\x1a\x1e.infaas.internal.ScaleResponse\"\x00\x12_\n\x0cMigrateModel\x12%.infaas.internal.CreateMigrateRequest\x1a&.infaas.internal.CreateMigrateResponse\"\x00\x12^\n\x0b\x43reateModel\x12%.infaas.internal.CreateMigrateRequest\x1a&.infaas.internal.CreateMigrateResponse\"\x00\x12U\n\x0eProfileVariant\x12\x1f.infaas.internal.ProfileRequest\x1a .infaas.internal.ProfileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infaas.proto.internal.sys_monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCALEREQUEST']._serialized_start=111
  _globals['_SCALEREQUEST']._serialized_end=161
  _globals['_SCALERESPONSE']._serialized_start=163
  _globals['_SCALERESPONSE']._serialized_end=232
  _globals['_CREATEMIGRATEREQUEST']._serialized_start=234
  _globals['_CREATEMIGRATEREQUEST']._serialized_end=310
  _globals['_CREATEMIGRATERESPONSE']._serialized_start=312
  _globals['_CREATEMIGRATERESPONSE']._serialized_end=406
  _globals['_PROFILEREQUEST']._serialized_start=408
  _globals['_PROFILEREQUEST']._serialized_end=514
  _globals['_PROFILERESPONSE']._serialized_start=516
  _globals['_PROFILERESPONSE']._serialized_end=609
  _globals['_SYSSTATUS']._serialized_start=612
  _globals['_SYSSTATUS']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
