# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infaas.proto import modelreg_pb2 as infaas_dot_proto_dot_modelreg__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infaas/proto/modelreg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelRegStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/infaaspublic.infaasmodelreg.ModelReg/Heartbeat',
                request_serializer=infaas_dot_proto_dot_modelreg__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_modelreg__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RegisterModel = channel.unary_unary(
                '/infaaspublic.infaasmodelreg.ModelReg/RegisterModel',
                request_serializer=infaas_dot_proto_dot_modelreg__pb2.ModelRegRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_modelreg__pb2.ModelRegResponse.FromString,
                _registered_method=True)


class ModelRegServicer:
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Register a model. The Variant-Generator/Profiler run behind this call
        (paper §3.2): one variant per GPU type, profiled on a worker of that type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelRegServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=infaas_dot_proto_dot_modelreg__pb2.HeartbeatRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_modelreg__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=infaas_dot_proto_dot_modelreg__pb2.ModelRegRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_modelreg__pb2.ModelRegResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infaaspublic.infaasmodelreg.ModelReg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infaaspublic.infaasmodelreg.ModelReg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelReg:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasmodelreg.ModelReg/Heartbeat',
            infaas_dot_proto_dot_modelreg__pb2.HeartbeatRequest.SerializeToString,
            infaas_dot_proto_dot_modelreg__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasmodelreg.ModelReg/RegisterModel',
            infaas_dot_proto_dot_modelreg__pb2.ModelRegRequest.SerializeToString,
            infaas_dot_proto_dot_modelreg__pb2.ModelRegResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
