# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infaas/proto/modelreg.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'infaas/proto/modelreg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from infaas.proto import request_reply_pb2 as infaas_dot_proto_dot_request__reply__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1binfaas/proto/modelreg.proto\x12\x1binfaaspublic.infaasmodelreg\x1a infaas/proto/request_reply.proto\"\xa4\x02\n\x0fModelRegRequest\x12\x11\n\tsubmitter\x18\x01 \x01(\t\x12\x19\n\x11grandparent_model\x18\x02 \x01(\t\x12\x14\n\x0cparent_model\x18\x03 \x01(\t\x12\x15\n\rfirst_variant\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x06 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x07 \x01(\x02\x12\x11\n\tframework\x18\x08 \x01(\t\x12\x0c\n\x04task\x18\t \x01(\t\x12\x13\n\x0b\x63onfig_name\x18\n \x01(\t\x12\x15\n\rprofile_image\x18\x0b \x01(\x0c\x12\x10\n\x08hardware\x18\x0c \x03(\t\x12\x11\n\treprofile\x18\r \x01(\x08\x12\x14\n\x0cprofile_json\x18\x0e \x01(\t\"P\n\x10ModelRegResponse\x12*\n\x06status\x18\x01 \x01(\x0b\x32\x1a.infaaspublic.RequestReply\x12\x10\n\x08variants\x18\x02 \x03(\t\">\n\x10HeartbeatRequest\x12*\n\x06status\x18\x01 \x01(\x0b\x32\x1a.infaaspublic.RequestReply\"?\n\x11HeartbeatResponse\x12*\n\x06status\x18\x01 \x01(\x0b\x32\x1a.infaaspublic.RequestReply2\xe8\x01\n\x08ModelReg\x12l\n\tHeartbeat\x12-.infaaspublic.infaasmodelreg.HeartbeatRequest\x1a..infaaspublic.infaasmodelreg.HeartbeatResponse\"\x00\x12n\n\rRegisterModel\x12,.infaaspublic.infaasmodelreg.ModelRegRequest\x1a-.infaaspublic.infaasmodelreg.ModelRegResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infaas.proto.modelreg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELREGREQUEST']._serialized_start=95
  _globals['_MODELREGREQUEST']._serialized_end=387
  _globals['_MODELREGRESPONSE']._serialized_start=389
  _globals['_MODELREGRESPONSE']._serialized_end=469
  _globals['_HEARTBEATREQUEST']._serialized_start=471
  _globals['_HEARTBEATREQUEST']._serialized_end=533
  _globals['_HEARTBEATRESPONSE']._serialized_start=535
  _globals['_HEARTBEATRESPONSE']._serialized_end=598
  _globals['_MODELREG']._serialized_start=601
  _globals['_MODELREG']._serialized_end=833
# @@protoc_insertion_point(module_scope)
