# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infaas.proto import podexec_pb2 as infaas_dot_proto_dot_podexec__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infaas/proto/podexec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorStub:
    """Client app -> Server. Same fields as the old JSON /infer, but the image is
    raw JPEG bytes (no base64) so there is no encode/decode cost and the payload
    is ~33% smaller.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/podexec.Executor/Infer',
                request_serializer=infaas_dot_proto_dot_podexec__pb2.InferRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_podexec__pb2.InferReply.FromString,
                _registered_method=True)


class ExecutorServicer:
    """Client app -> Server. Same fields as the old JSON /infer, but the image is
    raw JPEG bytes (no base64) so there is no encode/decode cost and the payload
    is ~33% smaller.
    """

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=infaas_dot_proto_dot_podexec__pb2.InferRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_podexec__pb2.InferReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'podexec.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('podexec.Executor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Executor:
    """Client app -> Server. Same fields as the old JSON /infer, but the image is
    raw JPEG bytes (no base64) so there is no encode/decode cost and the payload
    is ~33% smaller.
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/podexec.Executor/Infer',
            infaas_dot_proto_dot_podexec__pb2.InferRequest.SerializeToString,
            infaas_dot_proto_dot_podexec__pb2.InferReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerStub:
    """Server -> Worker. The server forwards the (resolved) model id and the raw
    image bytes; no second base64 round-trip.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/podexec.Worker/Run',
                request_serializer=infaas_dot_proto_dot_podexec__pb2.RunRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_podexec__pb2.RunReply.FromString,
                _registered_method=True)


class WorkerServicer:
    """Server -> Worker. The server forwards the (resolved) model id and the raw
    image bytes; no second base64 round-trip.
    """

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=infaas_dot_proto_dot_podexec__pb2.RunRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_podexec__pb2.RunReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'podexec.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('podexec.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker:
    """Server -> Worker. The server forwards the (resolved) model id and the raw
    image bytes; no second base64 round-trip.
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/podexec.Worker/Run',
            infaas_dot_proto_dot_podexec__pb2.RunRequest.SerializeToString,
            infaas_dot_proto_dot_podexec__pb2.RunReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
