# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infaas.proto import queryfe_pb2 as infaas_dot_proto_dot_queryfe__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infaas/proto/queryfe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub:
    """Interface exported by INFaaS frontend.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryOnline = channel.unary_unary(
                '/infaaspublic.infaasqueryfe.Query/QueryOnline',
                request_serializer=infaas_dot_proto_dot_queryfe__pb2.QueryOnlineRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_queryfe__pb2.QueryOnlineResponse.FromString,
                _registered_method=True)
        self.QueryOffline = channel.unary_unary(
                '/infaaspublic.infaasqueryfe.Query/QueryOffline',
                request_serializer=infaas_dot_proto_dot_queryfe__pb2.QueryOfflineRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_queryfe__pb2.QueryOfflineResponse.FromString,
                _registered_method=True)
        self.AllParentInfo = channel.unary_unary(
                '/infaaspublic.infaasqueryfe.Query/AllParentInfo',
                request_serializer=infaas_dot_proto_dot_queryfe__pb2.AllParRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_queryfe__pb2.AllParResponse.FromString,
                _registered_method=True)
        self.QueryModelInfo = channel.unary_unary(
                '/infaaspublic.infaasqueryfe.Query/QueryModelInfo',
                request_serializer=infaas_dot_proto_dot_queryfe__pb2.QueryModelInfoRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_queryfe__pb2.QueryModelInfoResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/infaaspublic.infaasqueryfe.Query/Heartbeat',
                request_serializer=infaas_dot_proto_dot_queryfe__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=infaas_dot_proto_dot_queryfe__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class QueryServicer:
    """Interface exported by INFaaS frontend.
    """

    def QueryOnline(self, request, context):
        """Online query, send input data in the payload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOffline(self, request, context):
        """Offline query, input data are stored on the cloud (out of scope: PLAN §0.4)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllParentInfo(self, request, context):
        """All parent models with a specific task and dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryModelInfo(self, request, context):
        """Query model information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOnline,
                    request_deserializer=infaas_dot_proto_dot_queryfe__pb2.QueryOnlineRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_queryfe__pb2.QueryOnlineResponse.SerializeToString,
            ),
            'QueryOffline': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOffline,
                    request_deserializer=infaas_dot_proto_dot_queryfe__pb2.QueryOfflineRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_queryfe__pb2.QueryOfflineResponse.SerializeToString,
            ),
            'AllParentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AllParentInfo,
                    request_deserializer=infaas_dot_proto_dot_queryfe__pb2.AllParRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_queryfe__pb2.AllParResponse.SerializeToString,
            ),
            'QueryModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryModelInfo,
                    request_deserializer=infaas_dot_proto_dot_queryfe__pb2.QueryModelInfoRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_queryfe__pb2.QueryModelInfoResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=infaas_dot_proto_dot_queryfe__pb2.HeartbeatRequest.FromString,
                    response_serializer=infaas_dot_proto_dot_queryfe__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infaaspublic.infaasqueryfe.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infaaspublic.infaasqueryfe.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query:
    """Interface exported by INFaaS frontend.
    """

    @staticmethod
    def QueryOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasqueryfe.Query/QueryOnline',
            infaas_dot_proto_dot_queryfe__pb2.QueryOnlineRequest.SerializeToString,
            infaas_dot_proto_dot_queryfe__pb2.QueryOnlineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOffline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasqueryfe.Query/QueryOffline',
            infaas_dot_proto_dot_queryfe__pb2.QueryOfflineRequest.SerializeToString,
            infaas_dot_proto_dot_queryfe__pb2.QueryOfflineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllParentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasqueryfe.Query/AllParentInfo',
            infaas_dot_proto_dot_queryfe__pb2.AllParRequest.SerializeToString,
            infaas_dot_proto_dot_queryfe__pb2.AllParResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasqueryfe.Query/QueryModelInfo',
            infaas_dot_proto_dot_queryfe__pb2.QueryModelInfoRequest.SerializeToString,
            infaas_dot_proto_dot_queryfe__pb2.QueryModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaaspublic.infaasqueryfe.Query/Heartbeat',
            infaas_dot_proto_dot_queryfe__pb2.HeartbeatRequest.SerializeToString,
            infaas_dot_proto_dot_queryfe__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
