# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infaas/proto/request_reply.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'infaas/proto/request_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n infaas/proto/request_reply.proto\x12\x0cinfaaspublic\"K\n\x0cRequestReply\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.infaaspublic.RequestReplyEnum\x12\x0b\n\x03msg\x18\x02 \x01(\t\"M\n\x0b\x41llParReply\x12\x12\n\nall_models\x18\x01 \x03(\t\x12*\n\x06status\x18\x02 \x01(\x0b\x32\x1a.infaaspublic.RequestReply\"t\n\x0fQueryModelReply\x12\x0f\n\x07img_dim\x18\x01 \x01(\x05\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x02\x12\x12\n\nall_models\x18\x03 \x03(\t\x12*\n\x06status\x18\x04 \x01(\x0b\x32\x1a.infaaspublic.RequestReply*=\n\x10RequestReplyEnum\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bUNAVAILABLE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infaas.proto.request_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTREPLYENUM']._serialized_start=324
  _globals['_REQUESTREPLYENUM']._serialized_end=385
  _globals['_REQUESTREPLY']._serialized_start=50
  _globals['_REQUESTREPLY']._serialized_end=125
  _globals['_ALLPARREPLY']._serialized_start=127
  _globals['_ALLPARREPLY']._serialized_end=204
  _globals['_QUERYMODELREPLY']._serialized_start=206
  _globals['_QUERYMODELREPLY']._serialized_end=322
# @@protoc_insertion_point(module_scope)
